extends: default

rules:
  truthy:
    check-keys: true
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
  indentation:
    indent-sequences: consistent
  document-start: disable
  line-length:
    max: 140
    allow-non-breakable-words: true
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
