services:
  asterisk:
    image: ghcr.io/${OWNER:-severinbraun}/${REPO:-asterisk}:${TAG:-latest}
    container_name: asterisk
    restart: unless-stopped
    network_mode: host
    environment:
      - DOORBIRD_USER=${DOORBIRD_USER}
      - DOORBIRD_PASS=${DOORBIRD_PASS}
      - HA_USER=${HA_USER}
      - HA_PASS=${HA_PASS}
      - RTP_START=${RTP_START:-10000}
      - RTP_END=${RTP_END:-20000}
      - ASTERISK_LOG_LEVEL=${ASTERISK_LOG_LEVEL:-notice}
    volumes:
      - asterisk-lib:/var/lib/asterisk
      - asterisk-log:/var/log/asterisk
volumes:
  asterisk-lib:
  asterisk-log:
