services:
  asterisk:
    image: ghcr.io/${OWNER:-severinbraun}/${REPO:-asterisk}:${TAG:-latest}
    container_name: asterisk
    network_mode: host
    restart: unless-stopped
    env_file:
      - ./deploy/.env
    volumes:
      # Eigene Konfiguration einbinden (empfohlen read-only).
      # Lege dazu ./config an und kopiere Basisdateien aus containers/asterisk/etc/asterisk hinein.
      - ./config:/etc/asterisk:ro
      # Persistenz
      - ./var:/var/lib/asterisk
      - ./log:/var/log/asterisk
