services:
  asterisk:
    image: ghcr.io/${OWNER}/${REPO}:latest
    container_name: asterisk
    restart: unless-stopped
    network_mode: "host"
    environment:
      EXTERNAL_ADDR: ${EXTERNAL_ADDR}   # z.B. 203.0.113.10 oder my.dyndns.tld
      LOCAL_NET: ${LOCAL_NET}           # z.B. 192.168.1.0/255.255.255.0
    volumes:
      - ./containers/asterisk/etc-asterisk:/etc/asterisk:ro
      - ./asterisk-spool:/var/spool/asterisk
      - ./asterisk-log:/var/log/asterisk
      - ./asterisk-lib:/var/lib/asterisk
