services:
  asterisk:
    image: ghcr.io/${OWNER:-severinbraun}/${REPO:-asterisk}:${TAG:-latest}
    network_mode: "host"              # oder Ports mappen, falls nicht möglich
    # ports:
    #   - "5060:5060/udp"
    #   - "5060:5060/tcp"
    #   - "10000-20000:10000-20000/udp"
    restart: unless-stopped
    volumes:
      - ./data/etc-asterisk:/etc/asterisk
      - ./data/lib-asterisk:/var/lib/asterisk
      - ./data/spool-asterisk:/var/spool/asterisk
      - ./data/log-asterisk:/var/log/asterisk
    environment:
      - TZ=Europe/Berlin
