---
name: "Lint"

"on":
  push:
    branches: ["main","master"]
  pull_request:
    branches: ["main","master"]
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hadolint (Dockerfile)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: containers/asterisk/Dockerfile

      - name: Shellcheck (entrypoint.sh)
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: containers/asterisk
          severity: warning

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v4
        with:
          file_or_dir: .
          config_file: .yamllint.yml
