name: Security Scan
"on":
  workflow_run:
    workflows: ["Lint"]
    types: [completed]
  workflow_dispatch:

jobs:
  scan:
    # Weiter nur bei Erfolg des vorangehenden Jobs
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      - name: Trivy Config scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: config
          scan-ref: .
          format: table
          ignore-unfixed: true
          severity: HIGH,CRITICAL
