---
name: "Security Scan"

"on":
  workflow_run:
    workflows: ["Lint"]
    types: ["completed"]
  workflow_dispatch: {}

jobs:
  scan:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy FS (CRITICAL,HIGH)
        uses: aquasecurity/trivy-action@0.21.0
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: "1"
          format: table
