name: Security Scan

"on":
  workflow_run:
    workflows: ["Lint"]
    types: [completed]
  workflow_dispatch:

jobs:
  trivy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy FS scan (repo)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1
